- selvpc/errors.go
- selvpc/errors_test.go
- selvpc/resource_selvpc_resell_floatingip_v2.go
- selvpc/resource_selvpc_resell_license_v2.go
- selvpc/resource_selvpc_resell_project_v2.go
- selvpc/resource_selvpc_resell_role_v2.go
- selvpc/resource_selvpc_resell_role_v2_test.go
- selvpc/resource_selvpc_resell_subnet_v2.go
- selvpc/resource_selvpc_resell_user_v2.go
Add helper errors functions in errors.go that can be used to provide
more sense into error messages.
For #17
> Errors: add more context with common functions

- Gopkg.lock
- selvpc/config.go
- selvpc/config_test.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/client.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/quotas/schemas.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
Use NewV2ResellClientWithEndpoint() function from the "go-selvpcclient" package.
Add basic unit tests.
Use latest "go-selvpcclient" with tuned HTTP timeouts.
For #14
> Config: simplify client initialization, use tuned HTTP timeouts.

- Gopkg.lock
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
Use "go-selvpcclient" package with tuned HTTP timeouts.
For #30
> Vendor: add go-selvpcclient 1.5.2

- website/docs/r/resell_subnet_v2.html.markdown
Remove the "type" argument that doesn't exist.
> Subnet: remove "type" argument from docs

- selvpc/resource_selvpc_resell_token_v2_test.go
Remove hardcoded accountName value in account-scoped acceptance test.
Get new accountName value from SEL_TOKEN environment variable.
For #41
> Resell V2 Token - fix acceptance test

- selvpc/provider.go
- selvpc/resource_selvpc_resell_crossregion_subnet_v2_test.go
Use lower-case for resource name.
> Resell V2 Cross-region subnets: use lower-case

- .travis.yml
- GNUmakefile
Remove `go get goimports` from .travis.yml, remove imports target from
GNUmakefile.
For #47
> Cleanup Travis and GNUmakefile files

- go.mod
- go.sum
- selectel/resource_selectel_vpc_crossregion_subnet_v2.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/schemas.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
- vendor/modules.txt
Use go-selvpcclient v1.8.1.
Don't read project_id from the first associated subnet but use parent cross_region_subnet value.
For #52
> VPC Cross-region subnet: fix project_id argument

- CHANGELOG.md
Set links to terraform-provider-selectel instead of
terraform-provider-aws.
> Changelog: fix links to repository

- .travis.yml
- README.md
Go version: use 1.12.x in docs and CI
Use Go 1.12.x version for CI tests and in README.md.
Readme: use Terraform v0.12.x in docs
Update Terraform version in docs.
CI: use golangci-lint v1.17.1 in tests
Use newer version of golangci-lint.
> Update Go, Terraform and GolangCI-Lint versions

- selectel/resource_selectel_vpc_project_v2.go
Custom hashQuotas function havent checked diff for the nested
"resource_quotas" set.
Standard Set diff function works perfectly with the "quotas" argument so
it's better to use it.
For #59
> Remove custom hashQuotas() for project quotas arg

- selectel/import_selectel_mks_cluster_v1_test.go
- selectel/import_selectel_mks_nodegroup_v1_test.go
- selectel/resource_selectel_mks_cluster_v1_test.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
Implement "testAccMKSClusterV1GetDefaultKubeVersion" that allows
to get the default Kubernetes version from the MKS API and use it in
acceptance tests.
Update all MKS acceptance tests.
For #74
> MKS V1: use default Kubernetes version in tests

- go.mod
- go.sum
- selectel/config.go
- selectel/errors.go
- selectel/errors_test.go
- selectel/import_selectel_domains_domain_v1_test.go
- selectel/provider.go
- selectel/resource_selectel_domains_domain_v1.go
- selectel/resource_selectel_domains_domain_v1_test.go
- vendor/github.com/selectel/domains-go/LICENSE
- vendor/github.com/selectel/domains-go/pkg/v1/client.go
- vendor/github.com/selectel/domains-go/pkg/v1/doc.go
- vendor/github.com/selectel/domains-go/pkg/v1/domain/doc.go
- vendor/github.com/selectel/domains-go/pkg/v1/domain/requests.go
- vendor/github.com/selectel/domains-go/pkg/v1/domain/requests_opts.go
- vendor/github.com/selectel/domains-go/pkg/v1/domain/schemas.go
- vendor/modules.txt
- website/docs/r/domains_domain_v1.html.markdown
- website/selectel.erb
For #71 
This PR adds "selectel_domains_domain_v1" resource implementation, acc-tests and docs.
Vendor domains-go v0.2.0 dependency to work with Selectel Domains API.
> Domains V1: add domain resource

- go.mod
- go.sum
- selectel/mks.go
- selectel/mks_test.go
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- vendor/github.com/selectel/mks-go/pkg/v1/client.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/schemas.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/requests.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/requests_opts.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/schemas.go
- vendor/modules.txt
- website/docs/r/mks_nodegroup_v1.html.markdown
Add nodegroup labels support for "selectel_mks_nodegroup_v1" resource.
Update acc-tests with doc.
Vendor mks-go v0.3.0.
For #87
> MKS Nodegroup V1: add labels support

- selectel/import_selectel_mks_nodegroup_v1_test.go
- selectel/resource_selectel_mks_nodegroup_v1.go
Update "resourceMKSNodegroupV1Read" method to import nodegroup properly.
Update "TestAccMKSNodegroupV1ImportBasic".
For #89
> MKS Nodegroup V1: fix resource import

- go.mod
- go.sum
- selectel/mks.go
- selectel/mks_test.go
- vendor/github.com/selectel/mks-go/pkg/v1/client.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/requests.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/schemas.go
- vendor/modules.txt
- website/docs/r/mks_cluster_v1.html.markdown
Add support for Kubernetes minor version upgrade in `selectel_mks_cluster_v1` resource.
Update kube version helper functions with tests.
Update website documentation.
Vendor mks-go v0.4.0 dependency.
For #92
> MKS Cluster V1: add minor version upgrade support

- selectel/resource_selectel_mks_nodegroup_v1.go
Return an error in case when nodegroup ID is empty.
For #99
> MKS Nodegroup V1: fix Create method

- selectel/resource_selectel_mks_cluster_v1.go
Add DiffSuppressFunc for cluster "name" attribute that provides
support for uppercase cluster name in the terraform config.
For #101
> MKS Cluster V1: add uppercase name support

- selectel/resource_selectel_vpc_keypair_v2.go
Don't set "regions" in resourceVPCKeypairV2Read method to avoid
resource replacement in case of an empty value in the config.
For #102
> VPC Keypair V2: fix Read method

- selectel/import_selectel_vpc_keypair_v2_test.go
Update "TestAccVPCV2KeypairImportBasic".
For #105
> VPC Keypair V2: fix import test

- go.mod
- go.sum
- selectel/resource_selectel_vpc_project_v2.go
- selectel/resource_selectel_vpc_project_v2_test.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/quotas/requests_opts.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
- vendor/modules.txt
Vendor go-selvpcclient v1.11.1 that uses nullable strings for regions
and zones in quota options.
Update resourceVPCProjectV2QuotasOptsFromSet to use new types.
For #108
> VPC Project: fix empty regions and zones in quotas

- .golangci.yml
- .travis.yml
- selectel/provider_test.go
Use Golangci-lint v1.30.0 in Travis CI.
Remove deprecated enable-all configuration from .golangci.yml.
Fix issues with gofumpt linter in selectel/provider_test.go.
> Update and reconfigure golangci-lint

- go.mod
- go.sum
- selectel/resource_selectel_vpc_token_v2.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/keypairs/requests.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/quotas/requests_opts.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/requests.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/doc.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/requests_opts.go
- vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
- vendor/modules.txt
Vendor go-selvpcclient v1.12.0.
Use AccountName instead of DomainName in domain-scoped
resource_selectel_vpc_token_v2.
> Update go-selvpcclient and fix token resource

- .github/workflows/release.yml
- .gitignore
- README.md
Add GitHub Actions configuration for to publish releases.
Add Releasing the Provider section into README.md.
> GitHub Actions-based release pipeline

- README.md
Use the new link to repository in README.md.
Remove GOPATH since we're using Go 1.14.
> Update repository in README.md

- .github/workflows/acceptance-tests.yml
Pull requests from forks don't have secrets access.
Reference:
github.community/t/make-secrets-available-to-builds-of-forks/16166/32.
> Do not run acc tests for PRs

- go.mod
- go.sum
- selectel/mks.go
- selectel/mks_test.go
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- vendor/github.com/selectel/mks-go/pkg/v1/cluster/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/node/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/node/requests.go
- vendor/github.com/selectel/mks-go/pkg/v1/node/schemas.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/doc.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/requests_opts.go
- vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/schemas.go
- vendor/modules.txt
- website/docs/r/mks_nodegroup_v1.html.markdown
For #130 
Add 'taints' field into nodegroup resource.
Update tests and docs.
Vendor latest mks-go.
> MKS Nodegroup v1: taints support

- .github/workflows/acceptance-tests.yml
Use terraform_wrapper: false for hashicorp/setup-terraform@v1 in Acceptance tests.
> Disable wrapper for Terraform in acc tests

- README.md
> Remove GOPATH from README.md

- selectel/import_selectel_mks_cluster_v1_test.go
- selectel/import_selectel_mks_nodegroup_v1_test.go
- selectel/resource_selectel_mks_cluster_v1_test.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
Add `testAccMKSClusterV1GetMaintenanceWindowStart` function.
Update tests.
For #146
> MKS V1: fix maintenance window start time in tests

- selectel/resource_selectel_dbaas_datastore_v1.go
- selectel/resource_selectel_dbaas_datastore_v1_test.go
Change datastore's connection field type from TypeSet to TypeMap for
better output management.
> DBaaS V1: change connection field type

- .github/workflows/acceptance-tests.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- README.md
- go.mod
Hello. I am asking to increase golang version. It's need for [enabling darwin arm64 platform support](https://goreleaser.com/deprecations/#builds-for-darwinarm64).
> Increase golang version to 1.16

- go.mod
- go.sum
- selectel/data_source_selectel_dbaas_configuration_parameter_v1.go
- selectel/data_source_selectel_dbaas_configuration_parameter_v1_test.go
- selectel/provider.go
- selectel/resource_selectel_dbaas_database_v1_test.go
- selectel/resource_selectel_dbaas_datastore_v1.go
- selectel/resource_selectel_dbaas_datastore_v1_test.go
- selectel/resource_selectel_dbaas_extension_v1_test.go
- selectel/resource_selectel_dbaas_grant_v1_test.go
- selectel/resource_selectel_dbaas_user_v1_test.go
- vendor/github.com/selectel/dbaas-go/configuration_parameter.go
- vendor/github.com/selectel/dbaas-go/datastore.go
- vendor/modules.txt
- website/docs/d/dbaas_configuration_parameter_v1.html.markdown
- website/docs/r/dbaas_datastore_v1.html.markdown
- website/selectel.erb
Implement 'selectel_dbaas_configuration_parameter_v1' data source with acceptance test.
Add config options to create and update context for the datastore resource.
Vendor dbaas-go v0.2.0
For #162
> Add support for configuration parameters

- .gitignore
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- website/docs/r/mks_nodegroup_v1.html.markdown
Update selectel_mks_nodegroup_v1 resource with tests.
Update nodegroup resource documentation.
For #165
> MKS V1: add nodegroup autoscaling support

- go.mod
- go.sum
- selectel/data_source_selectel_dbaas_flavor_v1.go
- selectel/data_source_selectel_dbaas_flavor_v1_test.go
- selectel/resource_selectel_dbaas_datastore_v1.go
- selectel/resource_selectel_dbaas_datastore_v1_test.go
- vendor/github.com/selectel/dbaas-go/README.md
- vendor/github.com/selectel/dbaas-go/datastore.go
- vendor/github.com/selectel/dbaas-go/flavor.go
- vendor/modules.txt
- website/docs/d/dbaas_flavor_v1.html.markdown
- website/docs/r/dbaas_datastore_v1.html.markdown
Add redis_password field to datastore resource to create Redis datastores.
Add datastore_type_ids field to flavors.
Vendor dbaas-go v0.4.0.
For #173
> Add Redis to dbaas resources

- selectel/data_source_selectel_mks_kube_versions_v1.go
- selectel/data_source_selectel_mks_kube_versions_v1_test.go
- selectel/mks.go
- selectel/mks_test.go
- selectel/provider.go
- website/docs/d/mks_kube_versions_v1.html.markdown
- website/selectel.erb
Implement `selectel_mks_kube_versions_v1` data source with acceptance test.
Add helper functions in `mks.go` with needed tests.
Add `mks_kube_versions_v1` website page.
For #183
> MKS V1: add kube versions data source

- .github/workflows/golangci-lint.yml
Previously golangci-lint-action uses latest go version, but we need to use go1.17, because golangci-lint have some problems with go1.18. 
Now we will install configurable go version in additional step, and skip installing go in golangci-lint-action.
> fixes for golangci-lint job

- selectel/data_source_selectel_dbaas_flavor_v1_test.go
Hi!
TestAccDBaaSFlavorsV1Basic was failed because redis datastore type was added.
```
TF_ACC=1 go test github.com/terraform-providers/terraform-provider-selectel/selectel -run "^TestAccDBaaSFlavorsV1Basic$" -count=1
--- FAIL: TestAccDBaaSFlavorsV1Basic (107.96s)
data_source_selectel_dbaas_flavor_v1_test.go:23: Step 1/2 error: Check failed: Check 8/8 error: data.selectel_dbaas_flavor_v1.flavor_tf_acc_test_1: Attribute 'flavors.0.datastore_type_ids.#' expected "8", got "9"
FAIL
FAIL	github.com/terraform-providers/terraform-provider-selectel/selectel	108.278s
FAIL
```
Fixed it.
```
TF_ACC=1 go test github.com/terraform-providers/terraform-provider-selectel/selectel -run "^TestAccDBaaSFlavorsV1Basic$" -count=1
ok  	github.com/terraform-providers/terraform-provider-selectel/selectel	243.566s …
```
> Update test TestAccDBaaSFlavorsV1Basic

- .golangci.yml
- CHANGELOG.md
- go.mod
- go.sum
- selectel/domains.go
- selectel/resource_selectel_domains_record_v1.go
- selectel/resource_selectel_domains_record_v1_test.go
- website/docs/r/domains_record_v1.html.markdown
- Add support for ALIAS, CAA and SSHFP dns records
- Increase dupl threshold in golangci to pass test
> Add support for ALIAS, CAA and SSHFP DNS records

- .github/workflows/acceptance-tests.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- .golangci.yml
- README.md
- go.mod
- go.sum
- scripts/golangci_lint_check.sh
- selectel/dbaas.go
- selectel/domains.go
- selectel/mks.go
- selectel/resource_selectel_dbaas_extension_v1.go
- selectel/resource_selectel_dbaas_grant_v1.go
This PR closes #222
Changes:
- update: golang to v1.20,  golangci-lint to 1.51.1, updated to v3 actions: go-setup, checkout, golangci-lint-action
- change: golangci-lint.yml, remove deprecated linters
- fixed: linter issues
> update: golang to 1.20

- go.mod
- go.sum
- selectel/dbaas.go
- selectel/import_selectel_dbaas_postgresql_logical_replication_slot_v1_test.go
- selectel/provider.go
- selectel/resource_selectel_dbaas_postgresql_logical_replication_slot_v1.go
- selectel/resource_selectel_dbaas_postgresql_logical_replication_slot_v1_test.go
- website/docs/r/dbaas_postgresql_logical_replication_slot_v1.html.markdown.md
- website/selectel.erb
- Added resource to create logical replication slots for PostgreSQL - `selectel_dbaas_postgresql_logical_replication_slot_v1`
- Updated dbaas-go version to support logical replication slots API
- Added tests for logical replication slots resources
For: #214
> Added logical replication slots resources for PostgreSQL

- .gitignore
- .golangci.yml
- go.mod
- go.sum
- selectel/craas.go
- selectel/import_selectel_craas_registry_v1_test.go
- selectel/provider.go
- selectel/provider_test.go
- selectel/resource_selectel_craas_registry_v1.go
- selectel/resource_selectel_craas_registry_v1_test.go
- website/docs/r/craas_registry_v1.html.markdown
- website/selectel.erb
Implement `selectel_craas_registry_v1` resource with acceptance tests.
Add helper functions in `craas.go`.
Update the documentation.
Update .gitignore file.
All new acceptance tests are done:
```
=== RUN   TestAccCRaaSRegistryV1ImportBasic
--- PASS: TestAccCRaaSRegistryV1ImportBasic (55.13s)
=== RUN   TestAccCRaaSRegistryV1Basic
--- PASS: TestAccCRaaSRegistryV1Basic (62.31s)
PASS
ok      github.com/terraform-providers/terraform-provider-selectel/selectel     117.621s
```
> CRaaS V1: add registry resource

- selectel/craas.go
- selectel/provider.go
- selectel/resource_selectel_craas_token_v1.go
- selectel/resource_selectel_craas_token_v1_test.go
- website/docs/r/craas_token_v1.html.markdown
- website/selectel.erb
Implement `selectel_craas_token_v1` resource with acceptance test.
Update the documentation.
All related acceptance tests are done well:
```
=== RUN   TestAccCRaaSTokenV1Basic
--- PASS: TestAccCRaaSTokenV1Basic (59.30s)
PASS
ok      github.com/terraform-providers/terraform-provider-selectel/selectel     59.959s
```
> CRaaS V1: add token resource

- selectel/craas.go
- selectel/resource_selectel_craas_registry_v1.go
- selectel/resource_selectel_craas_registry_v1_test.go
- website/docs/r/craas_registry_v1.html.markdown
Add `endpoint` attribute to the `selectel_craas_registry_v1` resource.
Update the related acceptance test.
Update the documentation.
For #218
> CRaaS V1: extend schema for registry resource

- go.mod
- go.sum
- selectel/dbaas.go
- selectel/resource_selectel_dbaas_datastore_v1.go
- selectel/resource_selectel_dbaas_mysql_datastore_v1.go
- selectel/resource_selectel_dbaas_postgresql_datastore_v1.go
- selectel/resource_selectel_dbaas_redis_datastore_v1.go
- website/docs/r/dbaas_datastore_v1.html.markdown
- website/docs/r/dbaas_mysql_datastore_v1.html.markdown
- website/docs/r/dbaas_postgresql_datastore_v1.html.markdown
- website/docs/r/dbaas_redis_datastore_v1.html.markdown
To retain datastore backups more than seven days, we have to add new parameter that contains the number of backups retentions days
> Add backup retention days parameter to datastore

- selectel/resource_selectel_vpc_user_v2.go
We have server-side check for password strength, this PR will add client side validation with same restrictions
> Enforce password strength constraint

- go.mod
- go.sum
- selectel/dbaas.go
- selectel/provider.go
- selectel/resource_selectel_dbaas_kafka_acl_v1.go
- selectel/resource_selectel_dbaas_kafka_acl_v1_test.go
- selectel/resource_selectel_dbaas_kafka_datastore_v1.go
- selectel/resource_selectel_dbaas_kafka_datastore_v1_test.go
- selectel/resource_selectel_dbaas_kafka_topic_v1.go
- selectel/resource_selectel_dbaas_kafka_topic_v1_test.go
- website/docs/r/dbaas_kafka_acl_v1.html.markdown.md
- website/docs/r/dbaas_kafka_datastore_v1.html.markdown.md
- website/docs/r/dbaas_kafka_topic_v1.html.markdown
- website/selectel.erb
- Add a new resource selectel_dbaas_kafka_acl_v1 to manage Kafka's ACLs
- Add a new resource selectel_dbaas_kafka_topic_v1 to manage Kafka's Topics
- Add a new resource selectel_dbaas_kafka_datastore_v1 to manage Kafka datastores
- Update dbaas-go version to v0.10.0
> Add kafka support

- website/docs/r/dbaas_postgresql_extension_v1.html.markdown
It used to have copy pasted documentation from deprecated dbaas_extension resource. So it didn't get the updated documentation
> Fix dbaas_postgresql_extension resource doc

- go.mod
- go.sum
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- website/docs/r/mks_nodegroup_v1.html.markdown
* Add user data argument for `selectel_mks_nodegroup_v1`
* Add user data description to docs
* Update `mks-go`  version to v0.14.0
> Add user data support to MKS

- selectel/data_source_selectel_domains_rrset_v2.go
- selectel/data_source_selectel_domains_rrset_v2_test.go
- selectel/data_source_selectel_domains_zone_v2.go
- selectel/data_source_selectel_domains_zone_v2_test.go
- selectel/provider.go
- website/docs/d/domains_rrset_v2.html.markdown
- website/docs/d/domains_zone_v2.html.markdown
- website/selectel.erb
В [прошлом ПР](https://github.com/selectel/terraform-provider-selectel/pull/249), который включал в себя datasources для работы с zones и rrsets в нашем [DNS Hosting (actual)](https://docs.selectel.ru/networks-services/dns/about-dns/) в последний момент нас заставили их убрать. 
Теперь пришел запрос, что данные сущности необходимы для комфортной работы с нашем терраформ провайдером. 
Делаем новый ПР с добавлением этих сущностей и документации к ним.
Результаты запуска тестов:
```
=== RUN   TestAccDomainsZoneV2DataSourceBasic
--- PASS: TestAccDomainsZoneV2DataSourceBasic (68.31s)
PASS
ok      github.com/terraform-providers/terraform-provider-selectel/selectel     68.317s
=== RUN   TestAccDomainsRRSetV2DataSourceBasic
--- PASS: TestAccDomainsRRSetV2DataSourceBasic (69.36s)
PASS
ok …
```
> Added datasources for domains_v2 with docs

- selectel/schema_selectel_dbaas_postgresql_database_v1.go
Use default value instead of DiffSuppressFunc because of different behavior of the PostgreSQL and PostgreSQL-1C databases
> Use default value for the dbaas lc_* database fields

- go.mod
- go.sum
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- website/docs/r/mks_nodegroup_v1.html.markdown
* Add `install_nvidia_device_plugin` argument for `selectel_mks_nodegroup_v1`
* Add `install_nvidia_device_plugin` option to docs
* Update `mks-go` version to v0.15.0
* Update tests with nodegroup
> Add GPU without drivers and nvidia device plugin support to MKS

- selectel/dbaas_base_schemas.go
- selectel/schema_selectel_dbaas_datastore_v1.go
- selectel/schema_selectel_dbaas_mysql_datastore_v1.go
- selectel/schema_selectel_dbaas_postgresql_datastore_v1.go
- selectel/schema_selectel_dbaas_redis_datastore_v1.go
- website/docs/r/dbaas_mysql_datastore_v1.html.markdown
- website/docs/r/dbaas_postgresql_datastore_v1.html.markdown
- website/docs/r/dbaas_redis_datastore_v1.html.markdown
Set `7` as a default number of backup retention days for dbaas resources. It fixes a problem when after the second apply terraform tries to update `backup_retention_days` value to `null`
Closes #296
> Add default value for backup_retention_days field

- .github/workflows/secure.yml
- .semgrepignore
- GNUmakefile
- go.mod
- go.sum
- selectel/dbaas.go
- selectel/resource_selectel_mks_cluster_v1.go
- selectel/resource_selectel_mks_cluster_v1_test.go
- website/docs/r/mks_cluster_v1.html.markdown
**MKS**:
- Add `enable_audit_logs` argument for selectel_mks_cluster_v1
- Add `enable_audit_logs` option to docs
- Update `mks-go` version to v0.16.0
- Update tests with MKS cluster
**CI & build**:
- Remove broken semgrep rule `p/gitlab`
- Add ERROR severity to semgrep in CI
- Add semgrep to Makefile
- Add tests to .semgrepignore
> Add audit logs parameters support to MKS

- go.mod
- go.sum
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- website/docs/r/mks_nodegroup_v1.html.markdown
- Add `preemptible` argument for `selectel_mks_nodegroup_v1`
- Add `preemptible` option to docs
- Update `mks-go` version to v0.17.0
- Update tests
> Add preemptible nodegroups support to MKS

- selectel/resource_selectel_mks_nodegroup_v1.go
This PR will resolve https://github.com/selectel/terraform-provider-selectel/issues/300
Changes:
Add checking that, we can't use local_volume = false with not empty value for volume_type
> Add checking local_volume with volume_type 

- go.mod
- go.sum
- selectel/mks.go
- selectel/resource_selectel_mks_nodegroup_v1.go
- selectel/resource_selectel_mks_nodegroup_v1_test.go
- website/docs/r/mks_nodegroup_v1.html.markdown
* Updated the `mks-go` dependency from version `v0.18.0` to `v0.19.0`
* Added the `waitForMKSNodegroupV1ActiveState` function to wait for a nodegroup to reach the 'ACTIVE' state
* Modified the `resourceMKSNodegroupV1Read` function to set the `status` field of the nodegroup
* Updated the `resourceMKSNodegroupV1Update` to wait nodegroup status
* Updated tests
> Add support status for nodegroups MKS

- website/docs/r/mks_nodegroup_v1.html.markdown
Changes:
- Corrected the formatting of the `status` field description to use backticks for consistency with other field descriptions.
> Rewrite description of the status MKS nodegroup

- CHANGELOG.md
- go.mod
- go.sum
- selectel/mks.go
- selectel/resource_selectel_mks_cluster_v1.go
- selectel/resource_selectel_mks_cluster_v1_test.go
- website/docs/r/mks_cluster_v1.html.markdown
- Add `ca_certs` to `oidc`
- Fix updating `oidc`: cluster state does not change when it is not necessary
- Add oidc ca_certs to docs
- Update mks-go version to v0.20.0
- bump golang.org/x/net to v0.38.0
> Add CA certificates to OIDC params
