selectel/terraform-provider-selectel

README.md
Remove deprecation note that was moved from Selectel repository.
=> Readme: remove deprecation note

README.md
Update directory path to the latest url of the provider plugin.
For #6
=> Readme: update path in building section

Gopkg.lock, selvpc/import_selvpc_resell_subnet_v2_test.go, selvpc/provider.go, selvpc/resource_selvpc_resell_subnet_v2.go, selvpc/resource_selvpc_resell_subnet_v2_test.go, vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go, vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go, vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go, vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go, vendor/github.com/hashicorp/terraform/helper/validation/validation.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/requests.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/requests_opts.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/schemas.go, website/docs/r/resell_subnet_v2.html.markdown, website/selvpc.erb
Add Resell V2 Subnet resource with tests and documentation.
For #1
=> Resell V2 Subnet resource

Gopkg.lock, selvpc/import_selvpc_resell_role_v2_test.go, selvpc/provider.go, selvpc/resource_selvpc_resell_role_v2.go, selvpc/resource_selvpc_resell_role_v2_test.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/requests.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/requests_opts.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/schemas.go, website/docs/r/resell_role_v2.html.markdown, website/selvpc.erb
Add the "selvpc_resell_role_v2" resource with tests and documentation.
For #4
=> Resell V2: add Roles resource

selvpc/resource_selvpc_resell_floatingip_v2_test.go, selvpc/resource_selvpc_resell_license_v2_test.go, selvpc/resource_selvpc_resell_subnet_v2_test.go
Use var grouping in acceptance tests.
=> Internal: group variables in tests

website/docs/r/resell_user_v2.html.markdown
Fix Attributes section for the user resource.
=> Website: fix Resell V2 User docs

website/docs/r/resell_subnet_v2.html.markdown
Fix Example Usage section for the subnet resource.
=> Website: fix Resell V2 Subnet docs

Gopkg.lock, selvpc/provider.go, selvpc/resource_selvpc_resell_token_v2.go, selvpc/resource_selvpc_resell_token_v2_test.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/requests.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/requests_opts.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/schemas.go, website/docs/r/resell_token_v2.html.markdown, website/selvpc.erb
Add the "selvpc_resell_token_v2" resource with acceptance tests and documentation.
For #2
=> Resell V2: add Tokens resource

README.md
Add "Using the provider" section.
For #6
=> Readme: add usage section

Gopkg.lock, vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
Use "go-selvpcclient" package with tuned HTTP client.
=> Vendor: add go-selvpcclient 1.5.1

selvpc/errors.go, selvpc/errors_test.go, selvpc/messages.go, selvpc/messages_test.go, selvpc/provider.go, selvpc/resource_selvpc_resell_floatingip_v2.go, selvpc/resource_selvpc_resell_keypair_v2.go, selvpc/resource_selvpc_resell_license_v2.go, selvpc/resource_selvpc_resell_project_v2.go, selvpc/resource_selvpc_resell_role_v2.go, selvpc/resource_selvpc_resell_subnet_v2.go, selvpc/resource_selvpc_resell_token_v2.go, selvpc/resource_selvpc_resell_user_v2.go
This commit adds common functions to log Create/Update/Get and Delete
calls messages and fixes some common error messages to add more
information in them.
For #32
=> Refactor: unify debug messages

.travis.yml
=> CI: use GolangCI-Lint v1.12.5

.travis.yml, selvpc/config.go
=> CI: use Go 1.11.4

selvpc/servers.go
Remove checking if slice is empty.
=> Refactoring: remove redundant checks in servers.go

Gopkg.lock, selvpc/errors.go, selvpc/errors_test.go, selvpc/import_selvpc_resell_crossregion_subnet_v2_test.go, selvpc/networking.go, selvpc/networking_test.go, selvpc/provider.go, selvpc/regions.go, selvpc/regions_test.go, selvpc/resource_selvpc_resell_crossregion_subnet_v2.go, selvpc/resource_selvpc_resell_crossregion_subnet_v2_test.go, selvpc/resource_selvpc_resell_vrrp_subnet_v2.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests_opts.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/schemas.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/schemas.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go, website/docs/r/resell_crossregion_subnet_v2.html.markdown, website/selvpc.erb
Add "selvpc_resell_crossregion_subnet" resource with tests and docs.
For #24
=> ResellV2: add Cross-region subnet resource

.travis.yml
=> CI: use v1.15.0 release of GolangCI

.travis.yml
=> CI: use v1.16.0 release of GolangCI

.gitignore
Add files from Goland to gitignore.
=> Gitignore: add .idea

scripts/changelog-links.sh
Use "selectel" in changelog links.
=> Scripts: rename provider in changelog-links.sh

go.mod, go.sum, selectel/resource_selectel_vpc_token_v2.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/requests.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/users/doc.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/users/requests.go, vendor/modules.txt
Update go-selvpcclient and add support of revoke token
For #25
=> Resell V2: implement support of revoke token

.gitignore, .golangci.yml, .travis.yml
Update GolangCI version in .travis.yml.
Update .golangci.yml config.
Update .gitignore.
=> CI: use v1.19.1 release of GolangCI

selectel/import_selectel_vpc_user_v2_test.go, selectel/resource_selectel_vpc_user_v2.go
Add Importer into resource_selectel_vpc_user_v2.
Fix import_selectel_vpc_user_v2_test password field.
=> VPC V2 API: fix User importing

go.mod, go.sum, selectel/resource_selectel_vpc_floatingip_v2.go, selectel/resource_selectel_vpc_keypair_v2.go, selectel/resource_selectel_vpc_license_v2.go, selectel/resource_selectel_vpc_project_v2.go, selectel/resource_selectel_vpc_role_v2.go, selectel/resource_selectel_vpc_subnet_v2.go, selectel/resource_selectel_vpc_token_v2.go, selectel/resource_selectel_vpc_user_v2.go, selectel/resource_selectel_vpc_vrrp_subnet_v2.go, vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go, vendor/modules.txt
Check that response is not nil before trying to get error from it.
Update go-selvpcclient to the version with extended error messages.
For #60
=> Fix 404 error checks

.golangci.yml, .travis.yml
Use newer GolangCI-Lint in .travis.yml.
=> Update GolangCI-Lint to v1.23.8

README.md
=> Add kolsean

selectel/errors.go, selectel/import_selectel_mks_cluster_v1_test.go, selectel/import_selectel_mks_nodegroup_v1_test.go, selectel/mks.go, selectel/mks_test.go, selectel/provider.go, selectel/provider_test.go, selectel/resource_selectel_mks_nodegroup_v1.go, selectel/resource_selectel_mks_nodegroup_v1_test.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv/mutexkv.go, vendor/modules.txt, website/docs/r/mks_nodegroup_v1.html.markdown, website/selectel.erb
Implement "selectel_mks_nodegroup_v1" resource with acceptance test.
Add helper functions in "mks.go" with needed tests.
For: #74
=> MKS V1: add nodegroup resource

selectel/mks.go, selectel/mks_test.go, selectel/resource_selectel_mks_cluster_v1.go
Add kube version suppress diff function for MKS Cluster V1 resource.
For #84
=> MKS V1: add kube version suppress diff func

selectel/resource_selectel_mks_cluster_v1.go, selectel/resource_selectel_mks_nodegroup_v1.go
Increase default timeouts to 60 minutes for MKS resources.
For #94
=> MKS V1: increase default timeouts

go.mod, go.sum, vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode/hashcode.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv/mutexkv.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_config.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/set.go, vendor/github.com/hashicorp/terraform-plugin-sdk/httpclient/useragent.go, vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go, vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go, vendor/modules.txt
Vendor github.com/hashicorp/terraform-plugin-sdk v1.13.0.
=> Upgrade Terraform SDK

README.md
=> Add Daniil Rutskiy to the list of maintaners

.github/workflows/acceptance-tests.yml
Run scheduled tests before testing MKS cluster will enter MAINTENANCE
mode.
Fix job name.
=> Fix Acceptance Tests name and schedule

selectel/import_selectel_mks_cluster_v1_test.go, selectel/resource_selectel_mks_cluster_v1.go, selectel/resource_selectel_mks_cluster_v1_test.go, website/docs/r/mks_cluster_v1.html.markdown
Allow to create zonal clusters.
Update tests and documentation.
For #112
=> MKS Cluster V1: add zonal argument

.github/workflows/acceptance-tests.yml
Add hashicorp/setup-terraform@v1 Github Action into Acceptance Tests.
=> Install latest version of Terraform in acc tests

.github/workflows/acceptance-tests.yml
Update Acceptance Tests TF_LOG env.
=> Use TF_LOG=TRACE in acc tests

.github/workflows/acceptance-tests.yml, GNUmakefile
Remove TF_LOG and -v argument for go test.
=> Remove extra logs in Acceptance Tests

README.md
Remove ozerovandrei.
Remove dstdfx.
=> Update the list of maintainers

selectel/data_source_selectel_domains_domain_v1.go, selectel/data_source_selectel_domains_domain_v1_test.go, selectel/provider.go, website/docs/d/domains_domain_v1.html.markdown, website/selectel.erb
Implement `selectel_domains_domain_v1` data source with acceptance test.
Add `selectel_domains_domain_v1` website page.
For #128
=> Domains V1: add domain data source

.github/workflows/acceptance-tests.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, README.md, go.mod
=> Use Go 1.15

selectel/data_source_selectel_dbaas_flavor_v1.go, selectel/data_source_selectel_dbaas_flavor_v1_test.go, selectel/provider.go, website/docs/d/dbaas_flavor_v1.html.markdown
Implement "selectel_dbaas_flavor_v1" data source with acceptance test
For #150
=> DBaaS V1: add flavor data source

selectel/import_selectel_dbaas_user_v1_test.go, selectel/provider.go, selectel/resource_selectel_dbaas_datastore_v1.go, selectel/resource_selectel_dbaas_user_v1.go, selectel/resource_selectel_dbaas_user_v1_test.go, website/docs/r/dbaas_user_v1.html.markdown, website/selectel.erb
Implement "selectel_dbaas_user_v1" resource with acceptance test.
Set flavor to datastore only if flavor_id is empty.
For #150
=> DBaaS V1: add user resource

selectel/import_selectel_dbaas_database_v1_test.go, selectel/provider.go, selectel/resource_selectel_dbaas_database_v1.go, selectel/resource_selectel_dbaas_database_v1_test.go, website/docs/r/dbaas_database_v1.html.markdown
Implement "selectel_dbaas_database_v1" resource with acceptance test.
For #150
=> DBaaS V1: add database resource

selectel/import_selectel_dbaas_grant_v1_test.go, selectel/provider.go, selectel/resource_selectel_dbaas_grant_v1.go, selectel/resource_selectel_dbaas_grant_v1_test.go, website/docs/r/dbaas_grant_v1.html.markdown
Implement "selectel_dbaas_grant_v1" resource with acceptance test.
Use base test function for database tests.
For #150
=> DBaaS V1: add grant resource

.golangci.yml, selectel/import_selectel_dbaas_extension_v1_test.go, selectel/provider.go, selectel/resource_selectel_dbaas_database_v1.go, selectel/resource_selectel_dbaas_datastore_v1.go, selectel/resource_selectel_dbaas_extension_v1.go, selectel/resource_selectel_dbaas_extension_v1_test.go, selectel/resource_selectel_dbaas_grant_v1.go, selectel/resource_selectel_dbaas_user_v1.go, website/docs/r/dbaas_database_v1.html.markdown, website/docs/r/dbaas_datastore_v1.html.markdown, website/docs/r/dbaas_extension_v1.html.markdown, website/docs/r/dbaas_grant_v1.html.markdown, website/docs/r/dbaas_user_v1.html.markdown, website/selectel.erb
Implement "selectel_dbaas_extension_v1" resource with acceptance test
For #150
=> DBaaS V1: add extension resource

selectel/data_source_selectel_dbaas_configuration_parameter_v1.go, selectel/dbaas.go, selectel/resource_selectel_dbaas_datastore_v1.go
Fix datastore's resource importer
For #162
=> Add datastores config to the read resource

selectel/dbaas.go, selectel/import_selectel_dbaas_mysql_datastore_v1_test.go, selectel/resource_selectel_dbaas_mysql_database_v1_test.go, selectel/resource_selectel_dbaas_mysql_datastore_v1.go, selectel/resource_selectel_dbaas_mysql_datastore_v1_test.go, selectel/resource_selectel_dbaas_postgresql_datastore_v1.go, selectel/resource_selectel_dbaas_redis_datastore_v1.go
- Added mysql_native datastore type to mysql resource `selectel_dbaas_mysql_datastore_v1`
- Added tests for MySQL Native
=> Added MySQL Native support

selectel/resource_selectel_mks_nodegroup_v1.go, selectel/resource_selectel_mks_nodegroup_v1_test.go, website/docs/r/mks_nodegroup_v1.html.markdown
For https://github.com/selectel/terraform-provider-selectel/issues/273
* fixed resource_selectel_mks_nodegroup_v1
* added some new test cases for resource_selectel_mks_nodegroup_v1
* updated docs
=> fix: fix bug with flavors 

selectel/schema_selectel_dbaas_postgresql_database_v1.go
Change `owner` to `owner_id` for dbaas_postgresql_database resource
=> Fix postgresql database resource field name

website/docs/r/secretsmanager_certificate_v1.html.markdown
Fixed typos in secretsmanager_certificate_v1 documentation
=> Fix in secretsmanager_certificate_v1 documentation

.github/workflows/release.yml
* change --rm-dist to --clean due to https://goreleaser.com/deprecations/#-rm-dist
=> update release.yml workflow

CHANGELOG.md
* prepare for selectel_dbaas_firewall_v1 release
=> Prepare changelog for v5.3.0 relese

website/docs/r/mks_cluster_v1.html.markdown, website/docs/r/mks_nodegroup_v1.html.markdown
Update MKS resources documentation:
- Region value
- RAM value
- added required parameter `install_nvidia_device_plugin`
=> Update MKS resources documentation

website/docs/r/iam_saml_federation_certificate_v1.html.markdown, website/docs/r/iam_saml_federation_v1.html.markdown
Changes:
* update IAM SAML Federation documentation
=> Update IAM SAML Federation documentation

website/docs/d/mks_kubeconfig_v1.html.markdown
Changes:
- corrected order of CA and client certificates in example
- added decoding fix from b64 to PEM certificates
=> Fix MKS data source documentation

CHANGELOG.md, selectel/resource_selectel_mks_nodegroup_v1.go
This PR will fix https://github.com/selectel/terraform-provider-selectel/pull/324
Changes:
After changes in https://github.com/selectel/terraform-provider-selectel/pull/324 we got error with creating nodegroup via terraform provider. Changes in this PR will resolve this problem.
=> Add fix for creating nodegroup after fixing in #324

CHANGELOG.md, go.mod, go.sum, selectel/resource_selectel_mks_cluster_v1.go, selectel/resource_selectel_mks_nodegroup_v1.go
- Added filters to `quotas.GetProjectQuotas` calls
- `selectel/go-selvpcclient/v4` version upgraded to v.4.1.0
=> fix: Add filters to `quotas.GetProjectQuotas` method to prevent 207 response status

website/docs/r/vpc_subnet_v2.html.markdown
For private networks and subnets, you must use OpenStack resources.
=> Fix vpc-subnet-v2

website/docs/r/dbaas_datastore_v1.html.markdown, website/docs/r/dbaas_kafka_datastore_v1.html.markdown, website/docs/r/dbaas_mysql_datastore_v1.html.markdown, website/docs/r/dbaas_postgresql_datastore_v1.html.markdown
fix: correct docs for postgresql
=> update doc for dbaas_postgresql_datasore
